# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: courses-riak-write-coordinator-depl
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: courses-riak-write-coordinator
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: courses-riak-write-coordinator
#     spec:
#       volumes:
#         - name: courses-riak-write-schemas
#           persistentVolumeClaim:
#             claimName: courses-riak-write-schemas-pvc
#         # - name: courses-riak-write-storage
#         #   persistentVolumeClaim:
#         #     claimName: courses-riak-write-pvc
#       containers:
#         - env:
#             - name: CLUSTER_NAME
#               value: courses-riak-write-cluster
#           image: basho/riak-ts
#           name: courses-riak-write-coordinator
#           ports:
#             - containerPort: 8087
#             - containerPort: 8098
#           resources: {}
#           volumeMounts:
#             - name: courses-riak-write-schemas
#               mountPath: /etc/riak/schemas
#             # - name: courses-riak-write-storage
#             #   mountPath: /var/lib/riak
#       restartPolicy: Always
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: courses-riak-write-coordinator-srv
# spec:
#   ports:
#     - name: 'protobuf'
#       port: 8087
#       targetPort: 8087
#     - name: 'http'
#       port: 8098
#       targetPort: 8098
#   selector:
#     app: courses-riak-write-coordinator
