# stage 1
FROM node:16 As builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build:prod

#stage 2
FROM nginx:alpine
COPY --from=builder /app/dist/frontend/ /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf