# #### courses RIAK-quey  Schemas #####
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: courses-riak-query-schemas-pv
# spec:
#   # persistentVolumeReclaimPolicy: Retain
#   storageClassName: courses-riak-query-schemas-class
#   capacity:
#     storage: 50Mi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /mnt/milms/riak/courses/riak-query/schemas
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: courses-riak-query-schemas-pvc
#   labels:
#     app: courses-riak-query-schemas-pvc
# spec:
#   storageClassName: courses-riak-query-schemas-class
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Mi
