export enum Subjects {
  CourseCreated = 'course-created',
  CourseUpdated = 'course:updated',
  CourseDeleted = 'course:deleted',
  AssignmentCreated = 'assignment:created',
  AssignmentUpdated = 'assignment:updated',
  AssignmentDeleted = 'assignment:deleted',
  CourseMaterialCreated = 'course-material:created',
  CourseMaterialUpdated = 'course-material:updated',
  CourseMaterialDeleted = 'course-material:deleted',
  AssignmentMaterialCreated = 'assignment-material:created',
  AssignmentMaterialUpdated = 'assignment-material:updated',
  AssignmentMaterialDeleted = 'assignment-material:deleted',
  StudentDeliveryAssignmentCreated = 'student-delivery-assignment:created',
  StudentDeliveryAssignmentUpdated = 'student-delivery-assignment:updated',
  StudentDeliveryAssignmentDeleted = 'student-delivery-assignment:deleted',
  StudentDeliveryFileCreated = 'student-delivery-file:created',
  StudentDeliveryFileUpdated = 'student-delivery-file:updated',
  StudentDeliveryFileDeleted = 'student-delivery-file:deleted',
  UserSignUp = 'user:signup',
  UserSignIn = 'user:signin',
  UserSignOut = 'user:signout',
  UserUpdate = 'user:update',
}
